-- NutriLink factory detail board extensions.
-- Run this script once in the production Supabase SQL Editor.
-- All additions are nullable so existing orders continue to work without re-entry.

alter table public.nl_orders add column if not exists order_no text;
alter table public.nl_orders add column if not exists order_date date;
alter table public.nl_orders add column if not exists planned_production_days text;
alter table public.nl_orders add column if not exists actual_production_finish_date date;
alter table public.nl_orders add column if not exists planned_factory_dispatch_date date;
alter table public.nl_orders add column if not exists actual_factory_dispatch_date date;
alter table public.nl_orders add column if not exists planned_arrival_date date;
alter table public.nl_orders add column if not exists actual_arrival_date date;
alter table public.nl_orders add column if not exists logistics_method text;
alter table public.nl_orders add column if not exists packaging_ready_status text;
alter table public.nl_orders add column if not exists order_currency text;
alter table public.nl_orders add column if not exists order_amount numeric(18,4);
alter table public.nl_orders add column if not exists order_fx_rate numeric(18,8);
alter table public.nl_orders add column if not exists order_fx_rate_date date;
alter table public.nl_orders add column if not exists order_cny_amount numeric(18,4);
alter table public.nl_orders add column if not exists order_pm_name text;
alter table public.nl_orders add column if not exists actual_unit_cost numeric(18,4);
alter table public.nl_orders add column if not exists payment_due_date date;
alter table public.nl_orders add column if not exists payment_status text;
alter table public.nl_orders add column if not exists payment_amount numeric(18,4);
alter table public.nl_orders add column if not exists paid_amount numeric(18,4);
alter table public.nl_orders add column if not exists payment_date date;
alter table public.nl_orders add column if not exists manual_status text;
alter table public.nl_orders add column if not exists manual_status_reason text;

update public.nl_orders
set order_no = coalesce(nullif(order_no, ''), nullif(contract_no, ''), '订单-' || id::text),
    order_date = coalesce(order_date, created_at::date),
    planned_arrival_date = coalesce(planned_arrival_date, due_date),
    order_currency = coalesce(order_currency, 'CNY')
where order_no is null or order_date is null or planned_arrival_date is null or order_currency is null;

create table if not exists public.nl_factories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  cooperation_status text not null default '在合作',
  address text,
  contact_name text,
  contact_email text,
  qualifications jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.nl_factories (name)
select distinct factory_name from public.nl_orders
where factory_name is not null and btrim(factory_name) <> ''
on conflict (name) do nothing;

create table if not exists public.nl_order_payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.nl_orders(id) on delete cascade,
  payment_stage text,
  amount numeric(18,4),
  currency text,
  due_date date,
  payment_date date,
  status text,
  note text,
  created_by_name text,
  created_at timestamptz not null default now()
);
create index if not exists nl_order_payments_order_idx on public.nl_order_payments(order_id, payment_date desc);

alter table public.nl_factories enable row level security;
alter table public.nl_order_payments enable row level security;

-- The Railway service uses the Supabase service role. These policies keep direct
-- browser access closed while preserving the existing backend access pattern.
comment on table public.nl_factories is 'Factory master data used by the independent factory detail board';
comment on table public.nl_order_payments is 'Optional payment schedule for factory detail board';
