-- NutriLink factory order board v2
-- Idempotent migration for the confirmed order-detail board field model.

alter table public.nl_orders
  add column if not exists procurement_cost numeric(18,4);

-- Preserve the existing manually entered amount for legacy rows. New and edited
-- rows use procurement_cost * quantity in the application layer.
comment on column public.nl_orders.procurement_cost is
  'Unit procurement cost used to calculate order_amount; historical rows may be null';

-- Existing file metadata already supports arbitrary document_type values. These
-- comments document the canonical values used by the board for file linkage.
comment on column public.nl_files.document_type is
  'Canonical types include invoice, payment_voucher, finished_product_coa, free_sale_certificate, certificate_of_origin, health_certificate';

-- Keep a durable audit trail for changes that affect the factory board. The
-- service-role backend writes this table after successful final saves.
create table if not exists public.nl_order_change_log (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.nl_orders(id) on delete cascade,
  field_name text not null,
  field_label text not null,
  before_value text,
  after_value text,
  changed_by_name text,
  changed_by_role text,
  created_at timestamptz not null default now()
);
create index if not exists nl_order_change_log_order_idx
  on public.nl_order_change_log(order_id, created_at desc);
alter table public.nl_order_change_log enable row level security;

-- Backfill only when a legacy row has no procurement cost. We cannot infer a
-- unit cost safely from old order totals when quantity is non-numeric.
