-- NutriLink PMO workflow, milestones, reminders, comments and quotes.
-- Run once in the production Supabase SQL Editor.

alter table public.nl_files add column if not exists review_reason_tag text;
alter table public.nl_files add column if not exists review_due_date date;
alter table public.nl_files add column if not exists review_transfer_to text;

create table if not exists public.nl_milestones (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.nl_orders(id) on delete cascade,
  node_key text not null,
  node_name text not null,
  sequence integer not null,
  plan_date date,
  actual_date date,
  status text not null default '待开始',
  delay_reason text,
  updated_at timestamptz not null default now(),
  unique(order_id, node_key)
);
create index if not exists nl_milestones_order_sequence_idx on public.nl_milestones(order_id, sequence);

create table if not exists public.nl_reminders (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.nl_orders(id) on delete cascade,
  message text not null,
  created_by_name text not null,
  created_by_role text not null,
  target_role text not null default 'factory',
  read_at timestamptz,
  read_by_name text,
  created_at timestamptz not null default now()
);
create index if not exists nl_reminders_order_created_idx on public.nl_reminders(order_id, created_at desc);

create table if not exists public.nl_notifications (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.nl_orders(id) on delete cascade,
  kind text not null,
  title text not null,
  detail text,
  target_role text,
  created_by_name text not null,
  created_by_role text not null,
  read_at timestamptz,
  read_by_name text,
  created_at timestamptz not null default now()
);
create index if not exists nl_notifications_role_created_idx on public.nl_notifications(target_role, created_at desc);

create table if not exists public.nl_comments (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.nl_orders(id) on delete cascade,
  message text not null,
  mentions text,
  created_by_name text not null,
  created_by_role text not null,
  created_at timestamptz not null default now()
);
create index if not exists nl_comments_order_created_idx on public.nl_comments(order_id, created_at desc);

create table if not exists public.nl_quotes (
  id bigint generated by default as identity primary key,
  product_name text not null,
  factory_name text not null,
  currency text not null default 'USD',
  unit_price numeric(14,4) not null,
  moq text,
  sample_fee text,
  production_days text,
  payment_terms text,
  quoted_at date not null default current_date,
  note text,
  created_by_name text not null,
  created_at timestamptz not null default now()
);
create index if not exists nl_quotes_product_date_idx on public.nl_quotes(product_name, quoted_at);
create index if not exists nl_quotes_factory_product_idx on public.nl_quotes(factory_name, product_name);

-- This application accesses these tables only through the Railway service role.
-- Keep direct browser access closed.
alter table public.nl_milestones enable row level security;
alter table public.nl_reminders enable row level security;
alter table public.nl_notifications enable row level security;
alter table public.nl_comments enable row level security;
alter table public.nl_quotes enable row level security;
