-- NutriLink quote currency normalization and audit fields.
-- Run once in Supabase SQL Editor after the quote source migrations.

alter table public.nl_quotes add column if not exists cny_unit_price numeric(14,4);
alter table public.nl_quotes add column if not exists fx_rate_to_cny numeric(18,8);
alter table public.nl_quotes add column if not exists fx_rate_date date;
alter table public.nl_quotes add column if not exists fx_provider text;
alter table public.nl_quotes add column if not exists source_kind text not null default 'manual';
alter table public.nl_quotes add column if not exists submitted_by_name text;
alter table public.nl_quotes add column if not exists submitted_at timestamptz;

update public.nl_quotes
set source_kind = case when import_id is not null then 'import' else 'manual' end
where source_kind is null or source_kind = 'manual';

update public.nl_quotes
set submitted_by_name = coalesce(submitted_by_name, created_by_name),
    submitted_at = coalesce(submitted_at, created_at),
    fx_rate_to_cny = case when upper(coalesce(currency, 'CNY')) = 'CNY' then 1 else fx_rate_to_cny end,
    fx_rate_date = case when upper(coalesce(currency, 'CNY')) = 'CNY' then coalesce(fx_rate_date, quoted_at) else fx_rate_date end,
    fx_provider = case when upper(coalesce(currency, 'CNY')) = 'CNY' then coalesce(fx_provider, 'fixed') else fx_provider end,
    cny_unit_price = case when upper(coalesce(currency, 'CNY')) = 'CNY' then unit_price else cny_unit_price end;

create table if not exists public.nl_exchange_rates (
  id bigint generated by default as identity primary key,
  rate_date date not null,
  currency text not null,
  rate_to_cny numeric(18,8) not null check (rate_to_cny > 0),
  provider text not null,
  fetched_at timestamptz not null default now(),
  unique(rate_date, currency)
);

create index if not exists nl_quotes_cny_price_idx
  on public.nl_quotes(product_name, factory_name, quoted_at, cny_unit_price);

alter table public.nl_exchange_rates enable row level security;
