-- NutriLink quote filter option library. Run once in Supabase SQL Editor.

create table if not exists public.nl_quote_filter_options (
  id bigint generated by default as identity primary key,
  option_type text not null check (option_type in ('product', 'factory')),
  value text not null,
  created_by_name text not null,
  created_at timestamptz not null default now(),
  unique(option_type, value)
);

create index if not exists nl_quote_filter_options_type_value_idx
  on public.nl_quote_filter_options(option_type, value);

alter table public.nl_quote_filter_options enable row level security;
