-- NutriLink quote source imports. Run once in Supabase SQL Editor before deploying this feature.

create table if not exists public.nl_quote_imports (
  id bigint generated by default as identity primary key,
  display_name text not null,
  source_file_name text,
  storage_path text unique,
  uploaded_by_name text not null,
  uploaded_at timestamptz not null default now(),
  record_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.nl_quotes add column if not exists import_id bigint references public.nl_quote_imports(id) on delete set null;
alter table public.nl_quotes add column if not exists source_file_name text;
create index if not exists nl_quotes_import_idx on public.nl_quotes(import_id);
create index if not exists nl_quote_imports_uploaded_idx on public.nl_quote_imports(uploaded_at desc);

insert into storage.buckets (id, name, public) values ('nutrilink-quote-sources', 'nutrilink-quote-sources', false)
on conflict (id) do nothing;

alter table public.nl_quote_imports enable row level security;
