-- Date-specific foreign exchange cache for quote-to-CNY conversion.
-- The Railway service fetches historical rates from Frankfurter/ECB on demand.
-- Safe to run repeatedly in the Supabase SQL Editor.

create table if not exists public.nl_exchange_rates (
  id bigint generated by default as identity primary key,
  rate_date date not null,
  currency text not null,
  rate_to_cny numeric(18,8) not null check (rate_to_cny > 0),
  provider text not null default 'Frankfurter/ECB',
  fetched_at timestamptz not null default now(),
  unique (rate_date, currency)
);

create index if not exists nl_exchange_rates_date_currency_idx
  on public.nl_exchange_rates(rate_date, currency);
